### ISSUE TITLE
JSON conversion error

### ISSUE THREAD

**Issue by corviday** [pacificclimate/p2a-rule-engine#10]
I am getting an error `TypeError: Object of type 'Decimal' is not JSON serializable` while attempting to write the results of the `shm` rule.

**Comment by corviday** [comment]
This error went away when I added explicit casts to float to the affected rules immediately before the dump to json, but I haven't looked into the code enough to feel confident that's the right approach.

```python
    rules["rule_shm"] = float(rules["rule_shm"])
    rules["rule_6j-i-land"] = float(rules["rule_6j-i-land"])
```

**Comment by corviday** [comment]
[This branch](https://github.com/pacificclimate/p2a-rule-engine/compare/patch/11?expand=1) records the temporary solutions to this issue and #11 .

**Comment by nikola-rados** [comment]
I've been meaning to get to this for a while. I can't remember why I chose to use a `Decimal` rather than sticking to `float`. I think I know where to change this in the code and will give it a try.
