### ISSUE TITLE
Update `modelmeta` package

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/p2a-rule-engine#18]
Once the upgrades at [`modelmeta`](https://github.com/pacificclimate/modelmeta) are finished we want to bring the new package in here. This should not require much more than a requirements update, but it will be worth releasing a new version. This new version should be implemented into [`sandpiper`](https://github.com/pacificclimate/sandpiper) asap.

**Comment by rod-glover** [comment]
I don't see any dependency on `modelmeta` in either this repo or `sandpiper`. What am I missing?

If there are dependencies on `modelmeta` in this codebase, then we'll need to check and possibly modify the database queries made with it. Specifically, anything that references `DataFileVariable` will probably have to change (in a small way).
